# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Elevate User
        run: |
          sudo su
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        
      - name: Install virtual environment
        run: |
          pip3 install virtualenv
      
      - name: Make virtual environment
        run: |
          python3 -m venv env
          
      - name: Activate venv
        run: |
          source env/bin/activate
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Go into non-elevated User
        run: |
          exit
